### ISSUE TITLE
Greate work but too slow on large dataset

### ISSUE THREAD

**Issue by yuedeji** [JumpThanawut/HRSVM-Research#1]
Hi There,

First of all, this is a great work and open source makes it greater!

I try to use HRSVM on a large dataset, but it is too slow. There are 32 labels (4 layers) and 842,030 instances in the training dataset. It takes 4 days and only finishes 20/32. One reason is that HRSVM is using single thread. Could you make an embarrassingly parallel version, like just making the top-level for loop in parallel. Or you can tell me where I can make it run in parallel and I will do the coding job.

Thanks,
Yuede

**Comment by JumpThanawut** [comment]
Hi Yuede,

Thanks for your interest in our project. Unfortunately, the current implementation does not support multithreading. However, I can point you to the pieces of code that you may be able to modify

In the link below, you will find a for-loop that iterates over all classes in the hierarchical structure.
https://github.com/JumpThanawut/HRSVM-Research/blob/0a89de79df45a3f36b2bc0bf3ebeadf56e014f66/Source%20Code/HRSVM%20Verion%201.0.0.0/svm-train.cpp#L471

The training process which is the most time consuming is at
https://github.com/JumpThanawut/HRSVM-Research/blob/0a89de79df45a3f36b2bc0bf3ebeadf56e014f66/Source%20Code/HRSVM%20Verion%201.0.0.0/svm-train.cpp#L577

So, if you modify the code from for-loop to use a thread pool. You should be able to achieve multithreading.

Thanks,
Jump

**Comment by yuedeji** [comment]
Hi Jump,
Thanks  for your quick response. 
I used openmp to make the first for loop parallel (Line 471 in svm-train.cpp). I added the header file, and compiled with -fopenmp flag. The changed part is as following.

 472         #pragma omp parallel
 473         {
 474             #pragma omp for nowait
 475             for(i=0;i<class_no;i++)

But I get a segmentation fault (core dumped), could you take a look?
class 5 : creating model
class 31 : creating model
Segmentation fault (core dumped)

Best,
Yuede

**Comment by JumpThanawut** [comment]
Hi Yueda,

Sorry that I can't get back to you earlier, I have been very busy recently.

I do not think you can simply use openmp with default configuration. There are several shared objects that will be modified during the process. In order to fix this issue, we will need to deep copy all objects that will be modified inside the loop. Based on the current implementation, it will take a lot of effort to achieve this. If you decide to go down this path, please share the result when you finish.

Alternatively, we can do parallelism in LIBSVM which is the core engine we use to train SVM. According to https://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html, in section "How can I use OpenMP to parallelize LIBSVM on a multicore/shared-memory computer?", it can help speed up the training process of SVM. This will help if you have low number of classes and it takes a lot of time to train SVM (which I think it will help in your case with 32 labels and 842,030 instances).
However, it does not build multiple models (labels) in parallel so if you have high number of classes and it takes a few seconds to train each of them, this approach will not help.
This will not parallel other processes including feature selection and our RSVM post processing.

I made change and push to a new branch.
https://github.com/JumpThanawut/HRSVM-Research/tree/openmp_svm_training

It will be great if you can share the command you use for svm-train and your dataset. I may be able to try running on my machine and see whether this change can help in your case.

Thanks,
Jump

**Comment by yuedeji** [comment]
Hi Jump,

Thanks so much for the follow-up. 
I think parallelizing the training of a single class would be beneficial to my use case. I will try the new branch and see.
I can share my training data with you. What is your email?

Thanks,
Yuede

**Comment by JumpThanawut** [comment]
My email is thanawutanan@gmail.com
